export const testRunContent = {
  metaTitle: 'After Class - Try a date with us',
  metaDescription:
    'We match you, pick a midpoint cafe, set the date. You show up.',
  brand: 'After Class',
  tagline: 'The first move is showing up.',
  coverHeadline: 'Hey there! Want to try our idea?',
  coverKicker: '',
  coverSub:
    'We set up real cafe dates by hand. No app to download. Answer a few questions and we\'ll match you if you\'re a fit.',
  start: 'Start',
  continue: 'OK',
  back: 'Back',
  submit: 'Submit',
  submitting: 'Sending…',
  enterHint: 'Press Enter',
  coverStart: 'Hit Enter when you\'re ready',
  progressLabel: 'Form progress',
  pages: {
    1: {
      title: 'Before we start',
      statement:
        'We match you, pick a midpoint cafe, and set the date. You show up. Public daytime cafes only.',
      consentTitle: 'Can we use your info for this?',
      consent:
        'I agree After Class can collect and use my info to match me, set up dates, and improve the product, under their privacy terms.',
      consentHelper: 'You need to agree before you continue.',
      wantIn: 'Want to help us test this?',
      wantInHelper:
        'We\'re trying After Class with a small group first. If you sign up, you\'ll be one of our early testers!',
      wantInError: 'Pick yes or no to continue.',
    },
    2: {
      title: 'Campus',
      campus: 'Campus / school',
      campusHelper: 'Your school or main campus.',
      city: 'What city do you live in?',
      cityHelper: '(within metro manila only)',
      cityOther: 'Which city?',
    },
    3: {
      title: 'Who you are',
      fullName: 'Full name',
      age: 'Age',
      ageHelper: 'Must be 18 or above',
      email: 'School email',
      emailHelper: 'School domain preferred.',
      emailWarn:
        'That looks like a personal inbox. A school domain is easier to verify. You can still continue.',
      phone: 'Phone',
      phoneHelper: '',
      socials: 'Instagram handle',
      socialsHelper: 'Enter your Instagram handle.',
      contact: 'Message me on',
    },
    4: {
      title: 'Verification',
      statement:
        'We need proof you\'re real and school-verified.',
      face: 'Selfie holding your school ID',
      faceHelper:
        'One photo where your face and ID are both clear. Holding it up next to you is perfect.',
      faceTips: [
        'Room is well lit',
        'Face fully visible',
        'School ID readable in the frame',
        'No heavy filters',
      ],
      schoolId: 'Photo of school ID',
      schoolIdHelper: 'Enough to verify school.',
      isMe: 'This is me. I’ll show up as myself.',
    },
    5: {
      title: 'Matching basics',
      gender: 'Gender',
      genderOther: 'How do you identify?',
      meet: 'Who you want to meet',
      meetHelper: 'Pick all that apply.',
      meetOther: 'Who else do you want to meet?',
      school: 'School',
      year: 'Year level',
      area: 'Area you live or can leave from',
      areaHelper: 'Barangay, campus, or landmarks. Not your exact home address.',
      travel: 'Max travel time for midpoint',
      nearby: 'Okay if your match is from a nearby school?',
      dealbreakers: 'Dealbreakers',
      dealbreakersHelper: 'Add 3 short ones.',
      about: 'One line about you / what a good first date looks like for you',
      aboutHelper: '(one line is enough)',
      cafes: 'Preferred cafes / areas',
      refuse: 'Areas you refuse',
      cover: 'You cover your own expenses!',
      coverHelper:
        'That means commute and food — everyone pays their own way. No one covers anyone else.',
      coverAgree: 'I agree',
      coverDisagree: 'I disagree',
      coverError: 'Pick I agree or I disagree.',
      access: 'Accessibility needs',
    },
    6: {
      title: 'Schedule',
      when: 'When can you do a cafe date?',
      whenHelper: 'Next 4 weeks. Tap days, then pick a 2 or 3 hour window.',
      hardNos: 'Hard nos',
      hardNosHelper: 'Exams, work, etc.',
    },
    7: {
      title: 'Safety',
      statement: 'A few rules for how these dates work.',
      understandEarly: 'I understand this is a dry run, not the full app.',
      publicCafe: 'Public daytime cafe only.',
      cancelEarly: 'I’ll cancel early if I can’t make it / no-shows matter.',
      canReport: 'I can report a bad experience / leave anytime.',
      interview: 'Okay to be lightly interviewed after the date.',
      emergencyName: 'Emergency contact name',
      emergencyNameHelper: 'Recommended.',
      emergencyPhone: 'Emergency contact number',
      emergencyHelper: 'Recommended. Not shared with your match.',
    },
    8: {
      title: 'Data use',
      lines: [
        'What we collect: your answers, contact info, and a selfie with your school ID.',
        'Why: matching, scheduling, safety, product learning.',
        'Who sees it: founders only for now.',
        'How long: kept for this testing period, then deleted or minimized.',
        'You can ask us to delete your data.',
        'We won’t sell your data.',
        'Photos aren’t posted publicly.',
        'Midpoint is calculated by After Class; no home addresses shared between matches.',
        'We only share what’s needed for the date: first name, one photo, meetup details.',
      ],
      understand: 'I understand how my data will be used.',
    },
    9: {
      title: 'Submit',
      truth: 'Everything here is true.',
      howHeard: 'How you heard about this',
    },
  },
  endings: {
    matched: {
      headline: 'The first move is showing up.',
      body: 'You\'re on the list. We\'ll message you on Instagram or Messenger if you\'re matched. Public daytime cafe only. You can leave or report anytime.',
    },
    declined: {
      headline: 'All good. We’ll leave it here.',
      body: 'No signup stored. If you change your mind, you can come back to this page.',
    },
    under18: {
      headline: 'This is 18+ only.',
      body: 'Thanks for being straight with us. We can\'t include you in this run.',
    },
  },
  yes: 'Yes',
  no: 'No',
  optional: 'Optional',
  recommended: 'Recommended',
  cityOptions: [
    'Quezon City',
    'Manila',
    'Makati',
    'Pasig',
    'Taguig',
    'Mandaluyong',
    'San Juan',
    'Marikina',
    'Parañaque',
    'Las Piñas',
    'Muntinlupa',
    'Caloocan',
    'Malabon',
    'Navotas',
    'Valenzuela',
    'Pateros',
    'Other',
  ],
  contactOptions: ['Instagram', 'Messenger'] as const,
  genderOptions: ['Woman', 'Man', 'Non-binary', 'Other'] as const,
  meetOptions: ['Women', 'Men', 'Non-binary people', 'Other'] as const,
  yearOptions: [
    '1st year',
    '2nd year',
    '3rd year',
    '4th year',
    '5th year+',
    'Graduate',
  ] as const,
  travelOptions: ['20 minutes', '30 minutes', '45 minutes', '60+ minutes'] as const,
  uploadPrompt: 'Choose file',
  uploadReplace: 'Replace photo',
  fileTypes: 'JPG, PNG, WEBP, or HEIC. 5 MB max.',
} as const
