export const testRunContent = {
  metaTitle: 'After Class — Early Testing Signup',
  metaDescription:
    'Manual dry run: we match you, pick a midpoint cafe, set the date. You show up.',
  brand: 'After Class',
  tagline: 'The first move is showing up.',
  coverKicker: 'After Class — Early Testing',
  coverSub:
    'Early testing for After Class. We match you, pick a midpoint cafe, set the date. You show up.',
  start: 'Start',
  continue: 'Continue',
  back: 'Back',
  submit: 'Submit',
  submitting: 'Sending…',
  enterHint: 'Press Enter',
  progressLabel: 'Early testing progress',
  pages: {
    1: {
      title: 'Early testing',
      statement:
        'Early testing for After Class (manual dry run). We match you, pick a midpoint cafe, set the date. You show up. Public daytime cafe only.',
      consent:
        'I agree After Class can collect and use my info to run early testing, match me, set up dates, and improve the product, under their privacy terms.',
      consentHelper: 'Consent before you continue.',
      wantIn: 'Yes, I want in.',
      wantInHelper: 'Only continue if yes.',
    },
    2: {
      title: 'Campus',
      campus: 'Campus / school',
      campusHelper: 'Your school or main campus.',
      city: 'City corridor (Metro Manila)',
      cityHelper: 'e.g. QC, Manila, Makati, Pasig, etc.',
      cityOther: 'Which city or corridor?',
    },
    3: {
      title: 'Who you are',
      fullName: 'Full name',
      age: 'Age',
      ageHelper: 'Must be 18+. Under 18 ends the form.',
      email: 'School email',
      emailHelper: 'School domain preferred.',
      emailWarn:
        'That looks like a personal inbox. A school domain is easier to verify. You can still continue.',
      phone: 'Phone / WhatsApp',
      phoneHelper: 'For coordinating the date.',
      socials: 'Socials (IG etc.)',
      socialsHelper: 'Light verification. Not posted publicly.',
      contact: 'Contact preference',
    },
    4: {
      title: 'Verification',
      statement:
        'Early testing security: we need proof you’re real and school-verified.',
      face: 'Clear face photo',
      faceHelper: 'Well-lit, face visible, no heavy filters.',
      schoolId: 'Photo of school ID',
      schoolIdHelper: 'Enough to verify school.',
      isMe: 'This is me. I’ll show up as myself.',
    },
    5: {
      title: 'Matching basics',
      gender: 'Gender',
      genderOther: 'How do you describe it?',
      meet: 'Who you want to meet',
      school: 'School',
      year: 'Year level',
      area: 'Area you live or can leave from',
      areaHelper: 'Barangay, campus, or landmarks. Not your exact home address.',
      travel: 'Max travel time for midpoint',
      nearby: 'Okay if your match is from a nearby school?',
      dealbreakers: 'Dealbreakers',
      dealbreakersHelper: '3–5 short ones.',
      about: 'One line about you / what a good first date looks like for you',
      cafes: 'Preferred cafes / areas',
      refuse: 'Areas you refuse',
      cover: 'I can cover my own order.',
      coverHelper: 'Keeps dates simple.',
      access: 'Accessibility needs',
    },
    6: {
      title: 'Schedule',
      when: 'Days/times you can do a daytime cafe date in the next 2–4 weeks',
      whenHelper: 'Be specific (e.g. Tue/Thu after 1pm).',
      hardNos: 'Hard nos',
      hardNosHelper: 'Exams, work, etc.',
    },
    7: {
      title: 'Safety',
      statement: 'Safety rules for early testing.',
      understandEarly: 'I understand this is early testing, not the full app.',
      publicCafe: 'Public daytime cafe only.',
      cancelEarly: 'I’ll cancel early if I can’t make it / no-shows matter.',
      canReport: 'I can report a bad experience / leave anytime.',
      interview: 'Okay to be lightly interviewed after the date.',
      emergencyName: 'Emergency contact name',
      emergencyNameHelper: 'Recommended.',
      emergencyPhone: 'Emergency contact number',
      emergencyHelper: 'Recommended. Not shared with your match.',
    },
    8: {
      title: 'Data use',
      lines: [
        'What we collect: your answers, contact info, face photo, school ID photo.',
        'Why: matching, scheduling, safety, product learning.',
        'Who sees it: founders only for now.',
        'How long: kept for this testing period, then deleted or minimized.',
        'You can ask us to delete your data.',
        'We won’t sell your data.',
        'Photos aren’t posted publicly.',
        'Midpoint is calculated by After Class; no home addresses shared between matches.',
        'We only share what’s needed for the date: first name, one photo, meetup details.',
      ],
      understand: 'I understand how my data will be used.',
    },
    9: {
      title: 'Submit',
      truth: 'Everything here is true.',
      howHeard: 'How you heard about this',
    },
  },
  endings: {
    matched: {
      headline: 'The first move is showing up.',
      body: 'You’re on the list. We’ll message you on WhatsApp or email if you’re matched. Public daytime cafe only. You can leave or report anytime.',
    },
    declined: {
      headline: 'All good. We’ll leave it here.',
      body: 'No signup stored. If you change your mind, you can come back to this page.',
    },
    under18: {
      headline: 'Early testing is 18+ only.',
      body: 'Thanks for being straight with us. We can’t include you in this run.',
    },
  },
  yes: 'Yes',
  no: 'No',
  optional: 'Optional',
  recommended: 'Recommended',
  cityOptions: [
    'Quezon City',
    'Manila',
    'Makati',
    'Pasig',
    'Taguig',
    'Mandaluyong',
    'San Juan',
    'Marikina',
    'Parañaque',
    'Las Piñas',
    'Muntinlupa',
    'Caloocan',
    'Malabon',
    'Navotas',
    'Valenzuela',
    'Pateros',
    'Other',
  ],
  contactOptions: ['Email', 'WhatsApp', 'Either'] as const,
  genderOptions: ['Woman', 'Man', 'Non-binary', 'Self-describe'] as const,
  meetOptions: ['Women', 'Men', 'Non-binary people'] as const,
  yearOptions: [
    '1st year',
    '2nd year',
    '3rd year',
    '4th year',
    '5th year+',
    'Graduate',
  ] as const,
  travelOptions: ['20 minutes', '30 minutes', '45 minutes', '60+ minutes'] as const,
  uploadPrompt: 'Tap to add a photo',
  uploadReplace: 'Replace photo',
  fileTypes: 'JPG, PNG, or WEBP. 5 MB max.',
} as const
