export const testRunContent = {
  metaTitle: 'After Class Enlistment',
  metaDescription:
    'We match you, pick a midpoint cafe, set the date. You show up.',
  brand: 'After Class',
  tagline: 'The first move is showing up.',
  coverHeadline: 'Hey there! Want to try our idea?',
  coverKicker: '',
  coverSub:
    'We set up real cafe dates by hand. No app to download. Answer a few questions and we\'ll match you if you\'re a fit.',
  start: 'Start',
  continue: 'OK',
  back: 'Back',
  submit: 'Submit',
  submitting: 'Sending…',
  enterHint: 'Press Enter',
  coverStart: 'Hit Enter when you\'re ready',
  progressLabel: 'Form progress',
  pages: {
    1: {
      title: 'Before we start',
      statement:
        'We match you, pick a midpoint cafe, and set the date. You show up. Public daytime cafes only.',
      consentTitle: 'Can we use your info for this?',
      consentHelper:
        'We follow the Philippine Data Privacy Act. We only use your answers, contact info, and ID selfie to match you, set up dates, keep things safe, and improve After Class. Founders see it for this test. We don\'t sell it or post your photos. You can ask us to delete it anytime.',
      consent:
        'Yes, I agree After Class can collect and use my info under the Data Privacy Act for this alpha test.',
      consentError: 'You need to agree before you continue.',
      wantIn: 'Want to help us test this?',
      wantInHelper:
        'We\'re trying After Class with a small group first. If you sign up, you\'ll be one of our early testers!',
      wantInError: 'Pick yes or no to continue.',
    },
    2: {
      title: 'Campus',
      campus: 'Campus / school',
      campusHelper: 'Your school or main campus.',
      city: 'What city do you live in?',
      cityHelper: '(within metro manila only)',
      cityOther: 'Which city?',
    },
    3: {
      title: 'Who you are',
      fullName: 'What\'s your full name?',
      age: 'What\'s your age?',
      ageHelper: 'Must be 18 or above',
      email: 'What\'s your email?',
      emailHelper: 'Use your .edu.ph school email.',
      emailSchoolError: 'Please type your school email.',
      phone: 'Phone',
      phoneHelper: '',
      socials: 'What\'s your Instagram/Messenger?',
      socialsHelper: 'Enter your Instagram handle.',
      contact: 'Message me on',
    },
    4: {
      title: 'Verification',
      statement:
        'We need proof you\'re real and school-verified.',
      face: 'Selfie holding your school ID',
      faceHelper:
        'One photo where your face and ID are both clear. Holding it up next to you is perfect.',
      faceTips: [
        'Room is well lit',
        'Face fully visible',
        'School ID readable in the frame',
        'No heavy filters',
      ],
      schoolId: 'Photo of school ID',
      schoolIdHelper: 'Enough to verify school.',
      isMe: 'This is me. I’ll show up as myself.',
    },
    5: {
      title: 'Matching basics',
      gender: 'What\'s your gender?',
      genderOther: 'How do you identify?',
      meet: 'Who do you want to meet?',
      meetHelper: 'Pick all that apply.',
      meetOther: 'Who else do you want to meet?',
      school: 'What school do you go to?',
      year: 'What\'s your year level?',
      area: 'Area you live or can leave from',
      areaHelper: 'Barangay, campus, or landmarks. Not your exact home address.',
      travel: 'Max travel time for midpoint',
      nearby: 'Okay if your match is from a nearby school?',
      dealbreakers: 'Dealbreakers',
      dealbreakersHelper: 'Add 3 short ones.',
      about: 'How would you describe yourself?',
      aboutHelper: '',
      cafes: 'Preferred cafes / areas',
      refuse: 'Areas you refuse',
      cover: 'You cover your own expenses!',
      coverHelper:
        'That means commute and food. Everyone pays their own way. No one covers anyone else.',
      coverAgree: 'I agree',
      coverDisagree: 'I disagree',
      coverError: 'Pick I agree or I disagree.',
      access: 'Accessibility needs',
    },
    6: {
      title: 'Schedule',
      when: 'What date and time are you available?',
      whenHelper:
        'Pick any days in the next month or so. For each day, pick a 2 hour window.',
      hardNos: 'Hard nos',
      hardNosHelper: 'Exams, work, etc.',
    },
    7: {
      title: 'Safety',
      statement: 'A few rules for how these dates work.',
      understandEarlyTitle: 'Want to join the After Class alpha?',
      understandEarlyHelper:
        'This is an early tryout, not the finished app. We\'re still learning as we go, and you\'d be one of the first people testing it with us.',
      understandEarly:
        'Yes, I agree to join the After Class alpha test and help try it out.',
      publicCafe: 'Public daytime cafe only.',
      cancelEarly: 'Can you cancel 2 days before?',
      cancelEarlyHelper:
        'You can only cancel until 2 days before the actual meetup date. After that, we need you to show up.',
      cancelEarlyError: 'You need to agree before you continue.',
      canReport: 'I can report a bad experience / leave anytime.',
      interview: 'Can we talk with you after the date?',
      interviewHelper:
        'This is an early test, so we need to hear how it went. A short chat after, nothing formal. You have to be okay with that to join.',
      interviewError: 'You need to say yes to continue.',
      emergencyName: 'Emergency contact name',
      emergencyNameHelper: 'Recommended.',
      emergencyPhone: 'Emergency contact number',
      emergencyHelper: 'Recommended. Not shared with your match.',
    },
    8: {
      title: 'Data use',
      lines: [
        'What we collect: your answers, contact info, and a selfie with your school ID.',
        'Why: matching, scheduling, safety, product learning.',
        'Who sees it: founders only for now.',
        'How long: kept for this testing period, then deleted or minimized.',
        'You can ask us to delete your data.',
        'We won’t sell your data.',
        'Photos aren’t posted publicly.',
        'Midpoint is calculated by After Class; no home addresses shared between matches.',
        'We only share what’s needed for the date: first name, one photo, meetup details.',
      ],
      understand: 'I understand how my data will be used.',
    },
    9: {
      title: 'Submit',
      truth: 'Everything here is true.',
      howHeard: 'How you heard about this',
    },
  },
  endings: {
    matched: {
      headline: 'You\'re on the list!',
      body: 'We\'ll message you on Instagram or Messenger if you\'re matched. Public daytime cafe only. You can leave or report anytime.',
    },
    declined: {
      headline: 'All good. We’ll leave it here.',
      body: 'No signup stored. If you change your mind, you can come back to this page.',
    },
    graduated: {
      headline: 'This run is for current students.',
      body: 'Thanks for checking in. We\'re only matching people still in school right now.',
    },
    under18: {
      headline: 'This is 18+ only.',
      body: 'Thanks for being straight with us. We can\'t include you in this run.',
    },
  },
  yes: 'Yes',
  no: 'No',
  optional: 'Optional',
  recommended: 'Recommended',
  cityOptions: [
    'Quezon City',
    'Manila',
    'Makati',
    'Pasig',
    'Taguig',
    'Mandaluyong',
    'San Juan',
    'Marikina',
    'Parañaque',
    'Las Piñas',
    'Muntinlupa',
    'Caloocan',
    'Malabon',
    'Navotas',
    'Valenzuela',
    'Pateros',
    'Other',
  ],
  contactOptions: ['Instagram', 'Messenger'] as const,
  genderOptions: ['Woman', 'Man', 'Non-binary', 'Other'] as const,
  meetOptions: ['Women', 'Men', 'Non-binary people', 'Other'] as const,
  yearOptions: [
    '1st year',
    '2nd year',
    '3rd year',
    '4th year',
    '5th year',
    'Graduated',
    'Others',
  ] as const,
  schoolOptions: [
    'Adamson University',
    'Arellano University',
    'Asia Pacific College',
    'Ateneo de Manila University',
    'Centro Escolar University',
    'De La Salle University',
    'De La Salle-College of Saint Benilde',
    'Emilio Aguinaldo College',
    'Far Eastern University',
    'FEU Institute of Technology',
    'José Rizal University',
    'Lyceum of the Philippines University',
    'Mapúa University',
    'National University',
    'Pamantasan ng Lungsod ng Maynila',
    'Philippine Christian University',
    'Philippine Normal University',
    'Philippine School of Business Administration',
    'Polytechnic University of the Philippines',
    'San Beda University',
    'San Sebastian College-Recoletos',
    'St. Paul University Manila',
    'St. Scholastica\'s College Manila',
    'Technological Institute of the Philippines',
    'Technological University of the Philippines',
    'University of Asia and the Pacific',
    'University of the East',
    'University of the Philippines Diliman',
    'University of the Philippines Manila',
    'University of Santo Tomas',
    'Other',
  ] as const,
  travelOptions: ['20 minutes', '30 minutes', '45 minutes', '60+ minutes'] as const,
  uploadPrompt: 'Choose file',
  uploadReplace: 'Replace photo',
  fileTypes: 'JPG, PNG, WEBP, or HEIC. 5 MB max.',
} as const
